<?php
    $this->headTitle('Login - Demo InputFilter');
    $form->setName('login')
        ->setAttributes([
            'class'=>'form-horizontal',
            'id'=>'form-login',
            'action'=>'#'
        ]);

    $form->prepare();
        
?>

<div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
    <?= $this->form()->openTag($form) ?>
        <div class="form-group">
            <?= $this->formLabel($form->get('email')) ?>
            <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
                <?= $this->formElement($form->get('email')) ?>    
                <?= $this->formElementErrors($form->get('email')) ?>    
            </div>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('password')) ?>
            <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
                <?= $this->formElement($form->get('password')) ?>    
                <?= $this->formElementErrors($form->get('password')) ?>    
            </div>
        </div>
        
        <div class="form-group"> 
    <div class="col-md-offset-3 col-md-9">
      <div class="checkbox">
        <label><?= $this->formElement($form->get('remember')) ?>
            Ghi nhớ
        </label>
      </div>
    </div>
  </div>
  <div class="form-group"> 
    <div class="col-md-offset-3 col-md-9">
        
        <?= $this->formElement($form->get('submit')) ?>
        
        </div>
        </div>
         <?= $this->form()->closeTag() ?>
        
    </div>
</div>

