<?php
$form->prepare();
?>
<p></p>
<div class="row">
<?=$this->form()->openTag($form)?>
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <div class="form-group">   
            <label class="control-label col-sm-3" >
                <?=$this->formLabel($form->get('typeId'))?>
            </label>
            <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                <?=$this->formElement($form->get('typeId'))?>
            </div>
        </div>
    </div>
<?=$this->form()->closeTag($form)?>
</div>

<table class="table table-hover">
    <thead>
        <tr>
            <th>#</th>
            
            <th>Tên món</th>
         <th style="width:30%">Mô tả ngắn</th>
            <!-- <th>Chi tiết</th> -->
            <th>Đơn giá</th>
            <th>Khuyến mãi</th>
            
            <th>Hình ảnh </th>
        </tr>
    </thead>
    <tbody>
        
</tbody>
</table>


<script>
    $(document).ready(function(){
       
        $('#typeId').change(function(){
            $.post('<?=$this->url('food2')?>', {'typeId': $('#typeId').val()}, function(data){
                $('table tbody').html(data);
            })
        });

        $('#typeId').trigger('change');
    });
</script>