<?php
$title = "Sửa thông tin tài khoản";
$this->headTitle($title);

$form->get('username')->setAttribute('readonly', true);
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

?>
<h1 align = "center"><?=$title." ".$form->get('username')->getValue()?></h1>

<div class="row">
 
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-md-offset-2">
    <?=$this->flashMessenger()->render('error', ['alert', 'alert-danger']);?>
        <?=$this->form()->openTag($form)?>
        <?=$this->formElement($form->get('id'))?>
            <div class="form-group">   
                <label class="control-label col-sm-4" >
                    <?=$this->formLabel($form->get('username'))?>
                </label>
                <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                    <?=$this->formElement($form->get('username'))?>
                    <?=$this->formElementErrors($form->get('username'))?>
                </div>
            </div>
            <div class="form-group">   
                <label class="control-label col-sm-4" >
                <?=$this->formLabel($form->get('fullname'))?>
                </label>
                <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                    <?=$this->formElement($form->get('fullname'))?>
                    
                </div>
            </div>
            <div class="form-group">   
                <label class="control-label col-sm-4" >
                    <?=$this->formLabel($form->get('birthdate'))?>
                </label>
                <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                    <?=$this->formElement($form->get('birthdate'))?>
                    <?=$this->formElementErrors($form->get('birthdate'))?>
                    
                </div>
            </div>
            <div class="form-group">   
                <label class="control-label col-sm-4" >
                    
                    Giới tính:
                </label>
                <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                    
                    <?=$this->formElement($form->get('gender'))?>
                    
                </div>
            </div>
            <div class="form-group">   
                <label class="control-label col-sm-4" >
                    <?=$this->formLabel($form->get('address'))?>
                </label>
                <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                    <?=$this->formElement($form->get('address'))?>
                    
                </div>
            </div>
            <div class="form-group">   
                <label class="control-label col-sm-4" >
                    <?=$this->formLabel($form->get('email'))?>
                </label>
                <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                    <?=$this->formElement($form->get('email'))?>
                    <?=$this->formElementErrors($form->get('email'))?>
                    
                </div>
            </div>
            
            <div class="form-group">   
                <label class="control-label col-sm-4" >
                    <?=$this->formLabel($form->get('phone'))?>
                </label>
                <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                    <?=$this->formElement($form->get('phone'))?>                    
                </div>
            </div>
            <div class="form-group">   
                <label class="control-label col-sm-4" >
                    <?=$this->formLabel($form->get('role'))?>
                </label>
                <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                    <?=$this->formElement($form->get('role'))?>                    
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-md-8 col-md-offset-4">
                    <?=$this->formElement($form->get('btnSubmit'))?>
                </div>
            </div>
        <?=$this->form()->closeTag()?>
    </div>    
</div>

<div class="clearfix">

</div>


