<?php
$title = "Danh sach User";
$this->headTitle($title);


?>


<table class="table table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>Username</th>
            <th>Họ tên</th>
            <th>Ngày sinh</th>
            <th>Giới tính</th>
            <th>Địa chỉ</th>
            <th>Email</th>
            <th>Điện thoại</th>
        </tr>
    </thead>
    <tbody>
        <?php 
            $stt = 1;
            foreach($users as $user):
        ?>
        <tr>
            <td><?=$stt++?></td>
            <td><?=$user->getUsername()?></td>
            <td><?=$user->getFullname()?></td>
            <td><?=$user->getBirthdate()->format('d-m-Y')?></td>
            <td><?=$user->getGender()?></td>
            <td><?=$user->getAddress()?></td>
            <td><?=$user->getEmail()?></td>
            <td><?=$user->getPhone()?></td>
        </tr>
            <?php endforeach;?>
    </tbody>
</table>
