<?php
$title = "Danh sach User";
$this->headTitle($title);


?>

<h1><?=$title?></h1>
<?=$this->flashMessenger()->render('success', ['alert', 'alert-success']);?>
 <div class="pull-right"><a href="<?=$this->url('user', ['action'=>'register'])?>" class="btn btn-primary">Đăng ký</a></div>

<table class="table table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>Username</th>
            <th>Họ tên</th>
            <th>Ngày sinh</th>
            <th>Giới tính</th>
            <th>Địa chỉ</th>
            <th>Email</th>
            <th>Điện thoại</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php 
            $stt = 1;
            foreach($users as $user):
        ?>
        <tr>
            <td><?=$stt++?></td>
            <td><?=$user->getUsername()?></td>
            <td><?=$user->getFullname()?></td>
            <td><?=$user->getBirthdate()->format('d-m-Y')?></td>
            <td><?=$user->getGender()?></td>
            <td><?=$user->getAddress()?></td>
            <td><?=$user->getEmail()?></td>
            <td><?=$user->getPhone()?></td>
            <td>

                <a href="<?=$this->url('user', ['action' => 'edit'], ['query'=>['id'=>$user->getId()]])?>" class="btn-sm btn-warning">Sửa</a>
                <a href="<?=$this->url('user', ['action' => 'delete'], ['query'=>['id'=>$user->getId()]])?>" class="btn-sm btn-danger">Xóa</a>                
                <br>
                <a href="<?=$this->url('user', ['action' => 'changePassword'], ['query'=>['id'=>$user->getId()]])?>" class="btn-sm btn-info">Đổi mật khẩu</a>
            </td>
        </tr>
            <?php endforeach;?>
    </tbody>
</table>
