<?php
$title = "Quên mật khẩu";
$this->headTitle($title);

$form->setAttribute('class', 'form-horizontal');
$form->prepare();

?>
<h1 align = "center"><?=$title?></h1>

<div class="row">
 
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-md-offset-2">
    <?=$this->flashMessenger()->render('success', ['alert', 'alert-success']);?>
    <?=$this->flashMessenger()->render('error', ['alert', 'alert-danger']);?>
        <?=$this->form()->openTag($form)?>
            
            <?=$this->formElement($form->get('csrf'))?>

            <div class="form-group">   
                <label class="control-label col-sm-4" >
                    <?=$this->formLabel($form->get('email'))?>
                </label>
                <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                    <?=$this->formElement($form->get('email'))?>
                    <?=$this->formElementErrors($form->get('email'))?>
                    
                </div>
            </div>
            
            <div class="form-group">   
                <label class="control-label col-sm-4" >
                    <?=$this->formLabel($form->get('captcha_image'))?>
                </label>
                <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                    <?=$this->formElement($form->get('captcha_image'))?>
                    <?=$this->formElementErrors($form->get('captcha_image'))?>
                </div>
            </div>
            

            <div class="form-group">
                <div class="col-md-8 col-md-offset-4">
                    <?=$this->formElement($form->get('submit'))?>
                </div>
            </div>
        <?=$this->form()->closeTag()?>
    </div>    
</div>

<div class="clearfix">

</div>


