<?php
$title = "Đăng nhập tài khoản";
$this->headTitle($title);

$form->setAttribute('class', 'form-horizontal');
$form->prepare();

?>

<h1 align="center"><?=$title?></h1>

<div class="row">
 
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-md-offset-2">
    
        <?=$this->flashMessenger()->render('error', ['alert', 'alert-danger']);?>
        <?=$this->form()->openTag($form)?>
            <div class="form-group">   
                <label class="control-label col-sm-4" >
                    <?=$this->formLabel($form->get('username'))?>
                </label>
                <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                    <?=$this->formElement($form->get('username'))?>
                    <?=$this->formElementErrors($form->get('username'))?>
                </div>
            </div>
            <div class="form-group">   
                <label class="control-label col-sm-4" >
                    <?=$this->formLabel($form->get('password'))?>
                </label>
                <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                    <?=$this->formElement($form->get('password'))?>
                    <?=$this->formElementErrors($form->get('password'))?>
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-md-8 col-md-offset-4">
                    <?=$this->formElement($form->get('remember'))?>
                    <?=$this->formLabel($form->get('remember'))?>
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-md-8 col-md-offset-4">
                <div class="pull-left">
                        <a href="<?=$this->url('resetpassword')?>">Quên mật khẩu</a>
                </div>
                    <div class="pull-right">
                        <?=$this->formElement($form->get('submit'))?>
                    </div>
                </div>
            </div>
        <?=$this->form()->closeTag()?>
    </div>    
</div>

<div class="clearfix">

</div>


