<?php
$title = "Danh sách món ăn";
$this->headTitle($title);


?>

<h1 class="cen"><?= $this->escapeHtml($title) ?></h1>


<a href="<?=$this->url('foods',['controller'=>'FoodsController', 'action'=>'add'])?>" class="btn btn-primary  pull-right">Thêm món ăn</a>    

<!-- <?=$this->flashMessenger()->render('success',['alert', 'alert-success'])?> -->
<?= $this->flashMessenger()
            ->setMessageOpenFormat('<div%s>
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                                    &times;
                                </button>
                                <ul><li>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>')
            ->render('success',   array('alert', 'alert-dismissible', 'alert-success'));
    ?>

<table class="table table-hover">
    <thead>
        <tr>
            <th>#</th>
            <!-- <th>Mã món</th> -->
            <th>Tên món</th>
            <th>Tên loại</th>
            <th style="width:30%">Mô tả ngắn</th>
            <!-- <th>Chi tiết</th> -->
            <th>Đơn giá</th>
            <th>Khuyến mãi</th>
            <th>Hình ảnh</th>
            <th> </th>
        </tr>
    </thead>
    <tbody>
        <!-- <?php
            $stt=1;
             foreach($foods as $food): ?>
            <tr>
                <td><?= $stt++ ?></td>
                <!-- <td> <?= $food->id?> </td> -->
                <td> <?= $food->name?> </td>
                <td> <?= $food->name_type?> </td>
                <td> <?= $food->summary?> </td>
                <!-- <td> <?= $food->detail?> </td> -->
                <td> <?= $food->price?> </td>
                <td> <?= $food->promotion?> </td>
                <td> <img style="width:120px; height:120px" src="img/hinh_mon_an/<?= $this->escapeHtml($food->image)?>" alt="<?= $this->escapeHtml($food->name)?>" >  </td>
                <td>
                    <a href="<?=$this->url('foods',['controller'=>'FoodsController', 'action'=>'edit', 'id'=>$food->id])?>" class="btn btn-default">Sửa</a>    
                    <a href="<?=$this->url('foods',['controller'=>'FoodsController', 'action'=>'delete', 'id'=>$food->id])?>" class="btn btn-danger">Xóa</a>    
                    
                </tr>
<?php endforeach;?> -->
        <?php
               $stt = ($this->paginator->getCurrentPageNumber() - 1) * $this->paginator->getItemCountPerPage() + 1;
               if(count($this->paginator)):
             foreach($paginator as $food): ?>
            <tr>
                <td><?= $stt++ ?></td>
                <td> <?= $food['name'] ?> </td>
                <td> <?= $food['name_type'] ?> </td>
                <td> <?= $food['summary'] ?> </td>
                <td> <?= $food['price'] ?> </td>
                <td> <?= $food['promotion'] ?> </td>
                <td> <img style="width:120px; height:120px" src="img/hinh_mon_an/<?= $this->escapeHtml($food['image']) ?>" alt="<?= $this->escapeHtml($food['name']) ?>" >  </td>
                <td>
                    <a href="<?=$this->url('foods',['controller'=>'FoodsController', 'action'=>'edit', 'id' => $food['id']])?>" class="btn btn-default">Sửa</a>    
                    <a href="<?=$this->url('foods',['controller'=>'FoodsController', 'action'=>'delete', 'id'=>$food['id']]) ?>" class="btn btn-danger">Xóa</a>    
                    
                </tr>
<?php endforeach;
    endif;?>
    </tbody>
    
</table>
<?= $this->paginationControl(
    $this->paginator,
    'Jumping',
    'partial/bootstrap_paginator',
    ['route' => 'foods']
) ?>