
<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination
-->

<?php if ($this->pageCount): ?>
<ul class="pagination">
<!-- Previous page link -->

<?php if (isset($this->previous)): ?>
<li>   <a href="<?= $this->url($this->route);?>?page=<?= $this->previous; ?>">&laquo; Trước</a></li>
 
<?php else: ?>
  <li class="disabled"><a href="#"><span>&laquo; Trước</span></a></li>
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>

  <?php if ($page != $this->current): ?>
  <li>    <a href="<?= $this->url($this->route);?>?page=<?= $page; ?>">
        <?= $page; ?>
    </a>
    </li>
  <?php else: ?>
  <li class="active"><a href="#">    <?= $page; ?></a> </li>
  <?php endif; ?>
  
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>

<li>  <a href="<?= $this->url($this->route)?>?page=<?=$this->next; ?>">  Sau &raquo;</a> </li>
<?php else: ?>
  
<li class="disabled"><a href="#"><span> Sau &raquo;</span></a></li>
<?php endif; ?>

</ul>
<?php endif; ?>